name: CI pipeline

on:
  push:
    branches:
      - main # Changing the branch here would also work.
  pull_request:
    branches:
      - main
    types:
      - "opened"
      - "synchronize"

env:
  NODE_VERSION: "14.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install dependencies
        run: |
          npm install

      - name: build
        run: npm run build --if-present

      - name: test
        run: npm run test --if-present

      - name: eslint
        run: npm run eslint

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_V: true
          DEFAULT_BUMP: patch
